export * from './header/Header'
export * from './home/Home'
export * from './about/About'
export * from './skills/Skills'
export * from './services/Services'
export * from './qualification/Qualification'
export * from './testimonials/Testimonials'
export * from './contact/Contact'